# Declare variables to be passed into your templates.
# Variables using underscores (snake case) come from terraform output (https://github.com/petrzivny/infrastructure-skeleton)

# Use terraform output "app_environment" from infrastructure repo.
app_environment: prod

# Use terraform output "gcp_project_id" from infrastructure repo.
gcp_project_id: replace-me

image:
  path: replace-me
  imagePullPolicy: Always

# Use terraform output "app_gcp_service_account_name" from infrastructure repo.
# Or if you use your own infrastructure, use cloud provider service account identifier.
app_gcp_service_account_name: replace-me

# Use terraform output "app_k8_service_account_name" from infrastructure repo.
# Or if you use your own infrastructure, use k8 serviceAccount name which is known to cloud provider service account.
app_k8_service_account_name: replace-me

# Nginx ingress controller will route all request from {host} to your nginx service. If you want to test url with IP only, provide host header "www.example.com"
host: www.example.com

# Used only in prod (environmentName=prod) for redirecting e.g. example.cz -> www.example.cz or www.example.cz -> www.example.com
# redirectToMainHostFromTheseHosts: []
redirectToMainHostFromTheseHosts:
  - example.cz
  - example.com
  - www.example.com

isCiPipeline: false

letsencryptCertEmail: replace-me
