services:
  nginx:
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - local

  php:
    build:
      context: ../
      dockerfile: .docker/php/Dockerfile
    networks:
      local:

