services:
  nginx:
    extends:
      file: common-services.yaml
      service: nginx
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_nginx_prod
    build:
      target: deployment
    image: ${REGISTRY:-external_registry}/${PROJECT_NAME:-symfony-react-skeleton}/nginx

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_php_prod
    build:
      target: deployment
      args:
        - symfony_mode=prod
    image: ${REGISTRY:-external_registry}/${PROJECT_NAME:-symfony-react-skeleton}/php
#    environment:
#      DATABASE_DRIVER: pdo_pgsql
#      DATABASE_PORT: 5432
#      DATABASE_SERVER_VERSION: 15.3
#      DATABASE_HOST: postgres
#      DATABASE_NAME: develop
#      DATABASE_USER: develop
#      DATABASE_PASSWORD: develop

networks:
  public:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_public
    external: true
  backend:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_backend
    external: true
