services:
  nginx:
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_nginx_prod
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
      target: deployment
#    image: ${IMAGE_PATH:-external_registry/symfony-react-skeleton}/nginx
#    image: europe-west1-docker.pkg.dev/basic4-2542859/all-registry-europe-west1/symfony-react-skeleton/nginx
    image: totea1.azurecr.io/pricemonitor/nginx
    ports:
      - "82:8080"

  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_php_prod
    build:
      target: deployment
      args:
        - symfony_mode=prod
#    image: ${IMAGE_PATH:-external_registry/symfony-react-skeleton}/php
#    image: europe-west1-docker.pkg.dev/basic4-2542859/all-registry-europe-west1/symfony-react-skeleton/php
    image: totea1.azurecr.io/pricemonitor/php
#    environment:
#      DATABASE_DRIVER: pdo_pgsql
#      DATABASE_PORT: 5432
#      DATABASE_SERVER_VERSION: 16
#      DATABASE_HOST: postgres
#      DATABASE_NAME: develop
#      DATABASE_USER: develop
#      DATABASE_PASSWORD: develop

networks:
  local:
    name: ${PROJECT_NAME:-symfony-react-skeleton}

#docker run -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro -d petreastusdevsharedacr.azurecr.io/samples/nginx
#docker run -p 80:80 -v /home/petr/Projects/personal/symfony-react-skeleton/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro -d petreastusdevsharedacr.azurecr.io/samples/nginx
