services:
  nginx:
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_nginx
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
      target: base
    image: ${PROJECT_NAME:-symfony-react-skeleton}_nginx:1.29-alpine
    volumes:
      - ../fe/dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/nginx-health || exit 1" ]
      timeout: 5s
      retries: 3
      start_period: 2s
    network_mode: "service:php" # nginx now lives in php's network namespace - simulate sidecar in k8s
    depends_on:
      php:
        condition: service_healthy
  php:
    extends:
      file: common-services.yaml
      service: php
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_php
    build:
      target: local
      args:
        - symfony_mode=dev
    image: ${PROJECT_NAME:-symfony-react-skeleton}_php:8.5-fpm-alpine
    ports:
      - "81:8080"
    volumes:
      - ../api:/var/www/html
    healthcheck:
      test: [ "CMD", "sh", "bin/php-fpm-healthcheck.sh" ]
      timeout: 5s
      retries: 3
      start_period: 2s

  postgres:
    container_name: ${PROJECT_NAME:-symfony-react-skeleton}_postgres
    image: postgres:${DATABASE_SERVER_VERSION:-18}-alpine
    volumes:
      - database_data:/var/lib/postgresql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-app}
      POSTGRES_USER: ${DATABASE_USER:-app}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME:-app}", "-U", "${DATABASE_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432"
    networks:
      - local

networks:
  local:
    name: ${PROJECT_NAME:-symfony-react-skeleton}

volumes:
  database_data:
    name: ${PROJECT_NAME:-symfony-react-skeleton}_postgresql-data
