# Do not use this file if you don't want to use GCP Secret Manager
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app_k8_service_account_name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.app_gcp_service_account_name}}
