{{ if not .Values.isCiPipeline }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # The ACME server URL (use first line for testing or debugging because prod version of Let's encrypt has low limits for issuing new certificates)
{{/*    server: https://acme-staging-v02.api.letsencrypt.org/directory # staging version, high rate limits, untrusted by browsers*/}}
    server: https://acme-v02.api.letsencrypt.org/directory # prod version, low rate limits, trusted by browsers
    # Email address used for ACME registration
    email: {{ .Values.letsencryptCertEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ printf "%s-%s-%s" "letsencrypt" .Chart.Name .Values.app_environment | trunc 63 | trimSuffix "-" }}
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
{{ end }}
