apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "nginx" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.environmentName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "nginx" | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "nginx" | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"  # replace :latest with :commit-sha in CI build process
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
          ports:
            - containerPort: 8080
