apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app.kubernetes.io/name: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: php-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-app
        date: "{{ now | unixEpoch }}"  # replace :latest with :commit-sha in CI build process
    spec:
      # Comment next line if you don't want to use GCP Secret Manager
      serviceAccountName: {{ .Values.app_k8_service_account_name }}
      containers:
        - name: php
          image: {{ .Values.image.repository }}/{{.Chart.Name}}/php
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - bin/php-fpm-healthcheck.sh # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - bin/php-fpm-healthcheck.sh
                - --listen-queue=10 # fails if there are more than 10 processes waiting in the fpm queue
                - --accepted-conn=5000 # fails after fpm has served more than 5k requests, this will force the pod to reset, use with caution
            initialDelaySeconds: 0
            periodSeconds: 15
          ports:
            - containerPort: 9000
          lifecycle:
            postStart:
              exec:
                command:
                  - bin/postdeploy.sh
                  {{- if not .Values.fetch_external_secrets_in_post_deploy_script }}
                  - --skip-vault-fetch
                  {{- end }}
