apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "php" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 9000
