apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-php
  labels:
    app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "php" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    environment: {{ .Values.app_environment }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "php" | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-%s" .Chart.Name "php" | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        date: "{{ now | unixEpoch }}"  # replace :latest with :commit-sha in CI build process
    spec:
      # Comment next line if you don't want to use GCP Secret Manager
      serviceAccountName: {{ .Values.app_k8_service_account_name }}
      containers:
        - name: php
          image: {{ .Values.image.path | trimSuffix "/" }}/php
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          readinessProbe:
            exec:
              command:
                - bin/php-fpm-healthcheck.sh # a simple ping since this means it's ready to handle traffic
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - bin/php-fpm-healthcheck.sh
                - --listen-queue=10 # fails if there are more than 10 processes waiting in the fpm queue
                - --accepted-conn=5000 # fails after fpm has served more than 5k requests, this will force the pod to reset, use with caution
            initialDelaySeconds: 0
            periodSeconds: 15
          ports:
            - containerPort: 9000
          lifecycle:
            postStart:
              exec:
                command: [
                  '/bin/sh',
                  '-c',
                  'sleep 10 && echo -e "ENVIRONMENT_NAME={{ .Values.app_environment }}\nGCP_PROJECT_ID={{ .Values.gcp_project_id }}" >> .env.local && bin/postdeploy.sh {{ .Values.isCiPipeline | ternary "--skip-vault-fetch" "" }} 2&> /proc/1/fd/2'
                ]
