on:
  workflow_call:

jobs:
  php:
    runs-on: self-hosted
    steps:
      - name: Dump github context
        run: env

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .docker/php/Dockerfile
          target: deployment
          tags: php:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          build-args: |
            symfony_mode=prod
