# Just a temp CD job, will be replaced with Argo CD
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  all:
    runs-on: self-hosted
    name: prod (temp)
    steps:
      - name: Set kubectl default context
        run: |
          kubectl config use-context gke_basic4-2542859_europe-west1-b_all-gke

      - name: Deploy
        run: |
          helm upgrade --install --atomic --cleanup-on-fail --create-namespace --timeout 1m skeleton-prod .deploy/helm \
            --namespace skeleton-prod \
            --set app_environment=prod \
            --set gcp_project_id=basic4-2542859 \
            --set app_gcp_service_account_name=skeleton-prod-gke-workload@basic4-2542859.iam.gserviceaccount.com \
            --set app_k8_service_account_name=gcp-secret-manager-binding-service-account-for-skeleton-prod \
            --set host=skeleton.totea.cz \
            --set letsencryptCertEmail=peter.usmc@gmail.com \
            --set image.path=${{ inputs.image-name }}
