# Just a temp CD job, will be replaced with Argo CD
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  all:
    runs-on: self-hosted
    name: Helm***
    steps:
      - name: Set kubectl default context
        run: |
          kubectl config use-context gke_basic4-2542859_europe-west1-b_all-gke

      - name: Upgrade (or install) - idempotent
        run: |
          helm upgrade --install --atomic --cleanup-on-fail --create-namespace --timeout 1m symfony-react-skeleton .deploy/helm \
            --set environmentName=prod \
            --set image.nginx=${{ inputs.image-name }}/nginx \
            --set image.php=${{ inputs.image-name }}/php \

