on:
  workflow_call:

jobs:
  all:
    runs-on: self-hosted
    name: Helm
    steps:
      - name: Upgrade (or install) - idempotent
        run: |
          helm upgrade --install --atomic --cleanup-on-fail --create-namespace --timeout 1m symfony-react-skeleton .deploy --set image.repository=${{ vars.REGISTRY_NAME }}

