on:
  workflow_call:

jobs:
  all:
    runs-on: self-hosted
    name: all
    steps:
      - name: Push php image
        run: |
          docker push ${{ vars.REGISTRY_NAME }}/${GITHUB_REPOSITORY#*/}/php

      - name: Push nginx image
        run: |
          docker push ${{ vars.REGISTRY_NAME }}/${GITHUB_REPOSITORY#*/}/nginx
