on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  all:
    runs-on: self-hosted
    name: all
    steps:
      - name: Push php image
        run: |
          docker push ${{ inputs.image-name }}/php

      - name: Push nginx image
        run: |
          docker push ${{ inputs.image-name }}/nginx
