on:
  workflow_call:

jobs:
  lint:
    runs-on: self-hosted
    name: Lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # disable shallow checkout to prevent ct to "failed identifying charts to process"
          fetch-depth: "0"

      - name: helm lint
        run: |
          cd .deploy/helm && helm lint --strict --with-subcharts

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --all --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          eval $(minikube docker-env)
          kubectl config current-context
          helm upgrade --install --atomic --cleanup-on-fail --create-namespace --timeout 1m symfony-react-skeleton .deploy/helm
          kubectl get pods
#          ct install --all --target-branch ${{ github.event.repository.default_branch }} --chart-dirs .deploy --helm-extra-args "--timeout 1m"

      - name: Debug On Failure
        if: failure()
        run: |
          kubectl version --client -o yaml
          echo "=== GET ALL ==="
          kubectl -n chart-testing get all
          echo "=== DESCRIBE PODS ==="
          kubectl -n chart-testing describe pods
          echo "=== GET DEPLOY ==="
          kubectl -n chart-testing get deploy
          echo "=== LOGS ==="
          kubectl -n chart-testing logs -l app=workboard-teams-management
          echo "=== PREVIOUS LOGS ==="
          kubectl -n chart-testing logs -l app=workboard-teams-management --previous
