name: CI-pipeline

on: [push]

jobs:

#  build-test-image:
#    name: Build Test Image
#    uses: ./.github/workflows/_build-test-image.yaml
#
#  php-code-quality-tests:
#    needs: [build-test-image]
#    name: PHP Test
#    uses: ./.github/workflows/_tests-code-quality.yaml
#
#  react-tests:
#    name: React tests
#    uses: ./.github/workflows/_tests-react.yaml

  build-prod-images:
    name: Build Prod Images
    uses: ./.github/workflows/_build-prod-images.yaml

#  cleanup:
#    if: success() || failure()
##    needs: [php-code-quality-tests]
#    runs-on: self-hosted
#    steps:
#      - name: Remove php test docker image
#        run: |
#          docker image rm php-test:${{ github.sha }}
