name: CI-pipeline

on: [push]

jobs:

  build-nginx-prod-image:
    name: Build Prod Image
    uses: ./.github/workflows/_build-prod-image-nginx.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  build-php-test-image:
    name: Build Test Image
    uses: ./.github/workflows/_build-test-image-php.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  helm-tests:
    name: Helm test
    uses: ./.github/workflows/_tests-helm.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  php-code-quality-tests:
    needs: [build-php-test-image]
    name: PHP Test
    uses: ./.github/workflows/_tests-code-quality.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  build-php-prod-images:
    needs: [php-code-quality-tests, helm-tests]
    name: Build Prod Image
    uses: ./.github/workflows/_build-prod-image-php.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  push-prod-images:
    needs: [build-php-prod-images, build-nginx-prod-image]
    name: Push Prod Images
    uses: ./.github/workflows/_push-prod-images-to-registry.yaml
    with:
      image-name: ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}

  continuous-deployment:
    needs: [push-prod-images]
    if: github.ref == 'refs/heads/main'
    name: CD
    uses: ./.github/workflows/_cd.yaml

  cleanup:
    if: success() || failure()
    needs: [php-code-quality-tests]
    runs-on: self-hosted
    steps:
      - name: Remove php test docker image
        run: |
          docker image rm ${{ vars.REGISTRY_NAME }}/${{ github.event.repository.name }}/php-test:${{ github.sha }}
