name: CI-pipeline

on: [push]

jobs:

  build-test-images:
    name: Build Test Image
    uses: ./.github/workflows/_build-test-images.yaml

  php-code-quality-tests:
    needs: [build-test-images]
    name: PHP Test
    uses: ./.github/workflows/_tests-code-quality.yaml

  build-prod-images:
    needs: [php-code-quality-tests]
    name: Build Prod Images
    uses: ./.github/workflows/_build-prod-images.yaml

  cleanup:
    if: success() || failure()
    needs: [php-code-quality-tests]
    runs-on: self-hosted
    steps:
      - name: Remove php test docker image
        run: |
          docker image rm ${{ github.repository }}/php-test:${{ github.sha }}
